### ISSUE TITLE
Tmux 2.4 key binding commands changed

### ISSUE THREAD

**Issue by ervasive** [wincent/clipper#10]
What previously was defined as:
```
bind-key -t vi-copy Enter copy-pipe "nc localhost 8377"
```
in tmux >= 2.4 now should be:
```
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "nc localhost 8377"
```

UNIX domain socket - old:
```
bind-key -t vi-copy Enter copy-pipe "nc -U ~/.clipper.sock"
```

new:
```
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "nc -U ~/.clipper.sock"
```

**Comment by wincent** [comment]
Ah yes, good point. I changed this [in my dotfiles](https://github.com/wincent/wincent/blob/bff31c32e427c5913d1eed0b0c1b3da24e8ba8ba/roles/dotfiles/files/.tmux.conf#L143) a while ago, but forgot that the docs here also needed to be updated.
