### ISSUE TITLE
nc hang in ubuntu container

### ISSUE THREAD

**Issue by zhoupro** [wincent/clipper#18]
use  nc -q 1

nnoremap <leader>y :call system('nc -q 1 host.docker.internal 8377', @0)<CR>

**Comment by wincent** [comment]
Just to clarify, is that an example of a command which hangs, or a command which avoids a hang?

**Comment by zhoupro** [comment]
when use  nc  hostip  hostport;   the command will hang. add "-q  1", the command will exit after 1 sec.
I use nc [v1.10-41.1].   I also found nc is so mess.

**Comment by wincent** [comment]
Maybe try the `-N` switch as suggested [in the docs](https://github.com/wincent/clipper/blob/master/README.md#fixing-delays-when-sending-data-to-clipper-via-nc)?
