### ISSUE TITLE
netcat hangs

### ISSUE THREAD

**Issue by sdondley** [wincent/clipper#23]
I found that my version of netcat on Debian 10 (Buster) hangs.

I had to slap a `-q 1` into the netcat command's like so:

`nc -q 1 localhost 8377`

I don't know enough about netcat to know if this is a smart change or not. But it seems to work. Perhaps this fix should be documented?

**Comment by sdondley** [comment]
Someone had same problem: https://github.com/wincent/clipper/issues/18

Note: The -N switch is not an option on Debian.

**Comment by wincent** [comment]
> I don't know enough about netcat to know if this is a smart change or not. But it seems to work. Perhaps this fix should be documented?

I wouldn't say no to a PR that added this as a possible technique in [the Troubleshooting section](https://github.com/wincent/clipper/blob/master/README.md#troubleshooting) of the docs, similar to [this entry](https://github.com/wincent/clipper/blob/master/README.md#fixing-delays-when-sending-data-to-clipper-via-nc). I don't have a Debian machine myself, so I am reliant on third-party reports to suggest/verify these workarounds.

**Comment by sdondley** [comment]
OK, I'll write something up when I get a chance.

Since Ubuntu is based on Debian, my guess is at some point the -N switch went away on Ubuntu, too.
