### ISSUE TITLE
Usage on boxes that are both local and remote

### ISSUE THREAD

**Issue by wincent** [wincent/clipper#26]
Example:

- Linux box as desktop: sometimes, I am physically using it, running Clipper out of systemd.
- Same Linux box as remote server: sometimes, I `ssh` into it, and want stuff forwarded back to Clipper on my Mac.

In the latter scenario, I'm not even sure what happens. The systemd instance of Clipper is listening on the socket. I'm using kitty on the Mac. It seems to be doing some magic, because when I paste (Command-V) I end up getting everything I've copied into Clipper on that machine... Did I set this up at some point and forget about it? Doesn't happen in iTerm, and doesn't show up when I inspect Clipboard on the Mac. Additionally, I don't recall setting up reverse port-forwarding to the Linux box in my `~/.ssh/config`.

**Comment by kovidgoyal** [comment]
You dont need all this machinery just to copy to clipboard over ssh. Just add support for OSC 52 to vim via oscyank.vim or similar (IIRC neovim comes with it out of the box). And for copying from the command line, use https://sw.kovidgoyal.net/kitty/kittens/clipboard/

**Comment by wincent** [comment]
Thanks @kovidgoyal! That explains some of the "magical" behavior I was seeing when using kitty. Helpful information!

Thing is, Clipper (2013) predates both Kitty (2016) and Neovim (2014), and so tries to be agnostic about what other tools you use — it isn't much "machinery" at all: at its heart, it is a [30-line Go function](https://github.com/wincent/clipper/blob/a72d38f73282edf8eca9ebb070b0934573dc880f/clipper.go#L400-L431) (most of which is logging/error handling) that does nothing more than send stuff from a socket to an executable. Because that's all it is, it means I can use it with any terminal emulator, with any editor, with or without tmux, locally or remotely. Using kitty instead would work on machines where I use kitty (at the moment, that's two out of three machines that I regularly use), but I need something that is going to work for me everywhere.

**Comment by kovidgoyal** [comment]
Of course, feel free to use whatever you like. Note that OSC 52 predates
kitty by a few years. Although widespread support for it in the larger
ecosystem is fairly recent.

**Comment by wincent** [comment]
Thanks to [kitty#8f214c51c092](https://github.com/kovidgoyal/kitty/commit/8f214c51c092d79e90fea25ec2e5db117af0054b), updating kitty solves the "getting everything I've copied" (instead of just the last thing) problem on the Linux box. 🥳 With no configuration, tmux now does the right thing in both kitty and iTerm2, so I think I can tweak my config to make Neovim and the shell do the right thing too for both of those, leaving Clipper as a fallback.

(See also: [this thread, which is a relatively recent list of support statuses](https://www.reddit.com/r/vim/comments/k1ydpn/a_guide_on_how_to_copy_text_from_anywhere/).)

**Comment by wincent** [comment]
Closing this as things are currently working to my satisfaction via [various](https://github.com/wincent/wincent/commit/696a13f17ac9c88e7a5b29ab6c79b5b42b7f239a) [hacks](https://github.com/wincent/wincent/commit/f0535c6c84c90104a8bd078f1ee3a3ade88242e7).
