### ISSUE TITLE
No error logs available when service is started with homebrew

### ISSUE THREAD

**Issue by bendavis78** [wincent/clipper#27]
I tried modifying `sudo vim /opt/homebrew/Cellar/clipper/2.0.0/homebrew.mxcl.clipper.plist` to tell clipper to use socket by default, but `brew services` showed an error when trying to start. There is nowhere to actually view that error. 

(also, is this the correct way to configure clipper to use socket on MacOS?)

**Comment by bendavis78** [comment]
Never mind, I just saw in the readme where mentions the error log location.

`~/Library/Logs/com.wincent.clipper.log`

**Comment by wincent** [comment]
Glad you got it sorted out!
