### ISSUE TITLE
How do you configure clipper installed via homebrew to use a unix socket by default?

### ISSUE THREAD

**Issue by bendavis78** [wincent/clipper#28]
When running clipper via `brew services start clipper`, I don't see a way to configure it to use a unix socket (for use in docker mount). How can this be done in a sustainable way?

**Comment by wincent** [comment]
You should be able to create a file at `~/.clipper.json` ([source](https://github.com/wincent/clipper/blob/8984a2e2eda5bca451ea4581031ffd3c3809356f/clipper.go#L166)) — for example:

```json
{
  "address": "~/.clipper.sock"
}
```

I'll close this, but let me know if this doesn't answer your question.
