### ISSUE TITLE
net.Listener() listens on all interfaces when no address is provided.

### ISSUE THREAD

**Issue by jeffreydwalter** [wincent/clipper#9]
Hey guys,
I don't use your project, but came across your commit here: https://github.com/wincent/clipper/commit/ae2800d534d0d60cc422c0ea23f2fd5c64898338

Based on the comments in this commit, I'm lead to believe that the intent is to only listen on the loopback address(es) when only the port is specified.

If that is the intent, then that code is broken. If not, then ignore me. :)

Here's the relevant net.Listen() example from the golang docs: https://golang.org/pkg/net/#example_Listener

Happy trails!

**Comment by wincent** [comment]
Well, that's a bummer. Guess I shouldn't have relied on that comment. (Just verified that what you say is true.) Will roll out a fix.

**Comment by wincent** [comment]
Thanks for the report. Just published 0.4.2 that fixes this.

**Comment by jeffreydwalter** [comment]
Happy to help! Since I was here, I took the liberty of looking over your commit, looks good to me.
